---
title: "CITS4009-Individual Project"
author: "Henry Tran"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Install all the required packages
library(ggplot2)

```

```{r}
# Read the data
path<-url("https://lms.uwa.edu.au/bbcswebdav/pid-3998436-dt-content-rid-47695412_1/courses/CITS4009_SEM-2_2024/Countries%20and%20death%20causes.csv")
```

# Data Exploratory
```{r}
data<-read.csv(path, header=TRUE)
head(data)
nrow(data)
```
The data has 31 columns and 6840 rows. For the column names, they can be seen that the column names have dot-separated between each word.

```{r}
names(data)<-gsub("\\.", " ", names(data)) #remove the dot in the column names

head(data)
```

```{r}
str(data)
```
```{r}
summary(data)
```
For the first 2 columns, "Entity" and "Code" store different country names and codes. Therefore, to set them as a country as a unique value, it would be the best to convert them into factor

```{r}
data$Entity<-as.factor(data$Entity)
data$Code<-as.factor(data$Code)

summary(data)
str(data)
```








